### ISSUE TITLE
Pretrained model shape mismatch

### ISSUE THREAD

**Issue by mohhao** [miemie2013/Paddle-YOLOv4#1]
Thanks for your great job，when I run train in notebook, have a runtime error, I'm not sure where to have a dimension 27 which mismatch 256 pretrained weights required, looking forward to a reply from you
```
Traceback (most recent call last):
  File "train.py", line 338, in <module>
    fluid.io.load_params(exe, cfg.model_path, main_program=startup_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 865, in load_params
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 741, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 808, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((27, 256, 1, 1)), while the loaded parameter (namely [ conv094.conv.weights ]) has a shape of  ((255, 256, 1, 1)).
```

**Comment by miemie2013** [comment]
> Thanks for your great job，when I run train in notebook, have a runtime error, I'm not sure where to have a dimension 27 which mismatch 256 pretrained weights required, looking forward to a reply from you
> -----------------~~~~~----------------------
> Now I know it caused by different classes number， I'm freshman in Paddle， how can I skip mismatch weights
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 338, in <module>
>     fluid.io.load_params(exe, cfg.model_path, main_program=startup_program)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 865, in load_params
>     filename=filename)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 741, in load_vars
>     filename=filename)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 808, in load_vars
>     format(orig_shape, each_var.name, new_shape))
> RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((27, 256, 1, 1)), while the loaded parameter (namely [ conv094.conv.weights ]) has a shape of  ((255, 256, 1, 1)).
> ```

it means that your num_classes is 4, have you ever modified coco_classes.txt?

**Comment by miemie2013** [comment]
> Thanks for your great job，when I run train in notebook, have a runtime error, I'm not sure where to have a dimension 27 which mismatch 256 pretrained weights required, looking forward to a reply from you
> -----------------~~~~~----------------------
> Now I know it caused by different classes number， I'm freshman in Paddle， how can I skip mismatch weights
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 338, in <module>
>     fluid.io.load_params(exe, cfg.model_path, main_program=startup_program)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 865, in load_params
>     filename=filename)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 741, in load_vars
>     filename=filename)
>   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 808, in load_vars
>     format(orig_shape, each_var.name, new_shape))
> RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((27, 256, 1, 1)), while the loaded parameter (namely [ conv094.conv.weights ]) has a shape of  ((255, 256, 1, 1)).
> ```

oh,I get it, you wanna train other datasets.I have not add the codes to skip mismatch weights.Perhaps you could refer to https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/index_cn.html
